name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - ALPINE_VERSION: "3.20"
            NODE_USE_CURRENT: "false"
          - ALPINE_VERSION: "3.21"
            NODE_USE_CURRENT: "false"
          - ALPINE_VERSION: "3.21"
            NODE_USE_CURRENT: "true"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          REPOS="\
            ${{ secrets.DOCKERHUB_USER }}/riscv-baseimage-node \
            ghcr.io/${{ github.repository }} \
          " \
          ALPINE_VERSION=${{ matrix.ALPINE_VERSION }} \
          NODE_USE_CURRENT=${{ matrix.NODE_USE_CURRENT }} \
          ./build.sh
